framework:
    mailer:
        message_bus: false
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'vault@alplight.ru'
        headers:
            From: 'System <vault@alplight.ru>'