version: '3'

services:
  cfh-app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - "APP_ENV=dev"
        - "APP_DEBUG=true"
    container_name: cfh
    restart: unless-stopped
    ports:
      - "0.0.0.0:8995:80"
    volumes:
      - "./:/cfh/cfh"
      - "./crypt:/crypt"
    privileged: true
    devices:
      - "/dev/fuse:/dev/fuse"
    environment:
      - "SYMFONY_DECRYPTION_SECRET=${SYMFONY_DECRYPTION_SECRET}"
      - "MIGRATION_DISABLED=${MIGRATION_DISABLED:-0}"
  cfh-db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-S0perPass}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###